### ISSUE TITLE
More asterisk support for z/OS ansible modules

### ISSUE THREAD

**Issue by cdlwhui** [IBM/z_ansible_collections_samples#147]
**Is your feature request related to a problem? Please describe.**

I have a playbook using zos_job_query to query jobname `"CPY*RS*"`
```
      zos_job_query:
        job_name: "CPY*RS*"
```
but it failed and  report the following error:
`Value of unknown type: <class 'RuntimeError'>, Failed to validate the job name: CPY*RS*\n`

```
      zos_job_query:
        job_name: "CPY*"
```

**Describe the solution you'd like**
It looks like only support asterisk * as the suffix of the jobname now.   
It would be better to have more than 1 asterisk support and even other wildcard support.

**Comment by ddimatos** [comment]
This is going to be tracked in the collections repository [here](https://github.com/ansible-collections/ibm_zos_core/issues/323).

**Comment by focabr** [comment]
Hi, 

i have the same problem here.

```yml
    - name: Lista todos as tasks do DB2
      zos_job_query:
        job_name: "D*MSTR"
      register: db2_query

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'RuntimeError'>, Failed to validate the job name: D*MSTR
```
I have test in version 1.3.5 and 1.4.0-beta.1
