### ISSUE TITLE
No ZOAU installation found meeting requirements (V1.0.3)

### ISSUE THREAD

**Issue by raylamgit** [IBM/z_ansible_collections_samples#64]
Hi Support,
I was wondering if ZOAU V1.0.3_ meets the requirements? Here is the log that I submitted host_setup.yaml.

[rlam@MVPAnsibleTower1 host_setup]$ ansible-playbook -i "tvt7111.svl.ibm.com,"  host_setup.yaml

PLAY [all] *****************************************************************************

TASK [Gather potential dependency paths] ***********************************************
changed: [tvt7111.svl.ibm.com]

TASK [set_fact] ************************************************************************
ok: [tvt7111.svl.ibm.com]

TASK [Assert potential python installs were found] *************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Assert potential ZOAU installs were found] ***************************************
skipping: [tvt7111.svl.ibm.com]

TASK [debug] ***************************************************************************
ok: [tvt7111.svl.ibm.com] => {
    "potential_paths": {
        "python": [
            {
                "interpreter": "/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8",
                "root": "/usr/lpp/IBM/cyp/v3r8/pyz"
            },
            {
                "interpreter": "/hsstools/python36/python-2017-04-12-py36/python36/bin/python3.6",
                "root": "/hsstools/python36/python-2017-04-12-py36/python36"
            }
        ],
        "zoau": [
            {
                "root": "/usr/lpp/IBM/zoautil"
            }
        ]
    }
}

TASK [Find valid python installation] **************************************************
included: /home/rlam/zSamples/z_ansible_collections_samples/zos_administration/host_setup/tasks/choose_python.yml for tvt7111.svl.ibm.com
included: /home/rlam/zSamples/z_ansible_collections_samples/zos_administration/host_setup/tasks/choose_python.yml for tvt7111.svl.ibm.com

TASK [Create temporary file] ***********************************************************
changed: [tvt7111.svl.ibm.com]

TASK [Write to temporary file] *********************************************************
changed: [tvt7111.svl.ibm.com]

TASK [Load variables from temp file] ***************************************************
ok: [tvt7111.svl.ibm.com]

TASK [Attempt to run ping command using newly discovered] ******************************
ok: [tvt7111.svl.ibm.com]

TASK [debug] ***************************************************************************
ok: [tvt7111.svl.ibm.com] => {
    "ping_response": {
        "changed": false,
        "failed": false,
        "failed_when_result": false,
        "ping": "pong"
    }
}

TASK [Determine if ping was successful] ************************************************
ok: [tvt7111.svl.ibm.com]

TASK [Set python installation] *********************************************************
ok: [tvt7111.svl.ibm.com]

TASK [Remove temporary file] ***********************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Create temporary file] ***********************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Write to temporary file] *********************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Load variables from temp file] ***************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Attempt to run ping command using newly discovered] ******************************
skipping: [tvt7111.svl.ibm.com]

TASK [debug] ***************************************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Determine if ping was successful] ************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Set python installation] *********************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Remove temporary file] ***********************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Assert a valid python install was found] *****************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Get ZOAU build dates] ************************************************************
changed: [tvt7111.svl.ibm.com]

TASK [debug] ***************************************************************************
ok: [tvt7111.svl.ibm.com] => {
    "zoau_build_dates": {
        "changed": true,
        "failed": false,
        "rc": 0,
        "stderr": "Shared connection to tvt7111.svl.ibm.com closed.\r\n",
        "stderr_lines": [
            "Shared connection to tvt7111.svl.ibm.com closed."
        ],
        "stdout": "2020/07/07 14:54:31 CUT V1.0.3\r\n",
        "stdout_lines": [
            "2020/07/07 14:54:31 CUT V1.0.3"
        ]
    }
}

TASK [Filter potential ZOAU options based on] ******************************************
ok: [tvt7111.svl.ibm.com]

TASK [Find valid ZOAU install] *********************************************************
included: /home/rlam/zSamples/z_ansible_collections_samples/zos_administration/host_setup/tasks/choose_zoau.yml for tvt7111.svl.ibm.com

TASK [Create temporary file] ***********************************************************
changed: [tvt7111.svl.ibm.com]

TASK [debug] ***************************************************************************
ok: [tvt7111.svl.ibm.com] => {
    "item": {
        "build": "1.0.3",
        "root": "/usr/lpp/IBM/zoautil"
    }
}

TASK [Write to temporary file] *********************************************************
changed: [tvt7111.svl.ibm.com]

TASK [Load variables from temp file] ***************************************************
ok: [tvt7111.svl.ibm.com]

TASK [Attempt to run zos_data_set using chosen dependency paths] ***********************
ok: [tvt7111.svl.ibm.com]

TASK [Set ZOAU installation if completed successfully] *********************************
skipping: [tvt7111.svl.ibm.com]

TASK [Remove temporary file] ***********************************************************
changed: [tvt7111.svl.ibm.com]

TASK [Remove temporary data set] *******************************************************
skipping: [tvt7111.svl.ibm.com]

TASK [Assert a valid ZOAU install was found] *******************************************
fatal: [tvt7111.svl.ibm.com]: FAILED! => {"changed": false, "msg": "No ZOAU installation found meeting requirements."}

PLAY RECAP *****************************************************************************
tvt7111.svl.ibm.com        : ok=22   changed=7    unreachable=0    failed=1    skipped=14   rescued=0    ignored=0

**Comment by ddimatos** [comment]
@raylamgit - I read over the log, I will look into this later in the week and try to reproduce and review the logic as its been a while since I have looked at this playbooks logic. 

ZOAU 1.0.3 should work with either of your python installations.  

In the mean time, you could manually set your environment host/group vars for IBM Enterprise python like so:
```
PYZ: "/usr/lpp/IBM/cyp/v3r8/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:/usr/sbin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
```
Your inventory  to:
``` 
zsystem:
  hosts:
    zvm:
      ansible_host: tvt7111.svl.ibm.com
      ansible_user: rlam
      ansible_python_interpreter: /usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8
```

**Optionally** to use the ROCKET installation you could set your environment host/group var to:
```
PYZ: "/hsstools/python36/python-2017-04-12-py36/python36"
ZOAU: "usr/lpp/IBM/zoautil"

environment_vars:
  ZOAU_ROOT: "{{ ZOAU }}"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib:{{ PYZ }}:/lib:/usr/lib"
  _BPXK_AUTOCVT: "ON"
  PATH: "{{ ZOAU }}/bin:/bin:/var/bin:{{ PYZ }}/bin"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
```

Your inventory to:
``` 
zsystem:
  hosts:
    zvm:
      ansible_host: tvt7111.svl.ibm.com
      ansible_user: rlam
      ansible_python_interpreter: /hsstools/python36/python-2017-04-12-py36/python36/bin/python3.6
```


Note that ZOAU 1.0.3 is failry old, many of our samples require something newer that 1.0.3, you can update your ZOAU with an unsupported version for no charge by [following this doc](https://www.ibm.com/docs/en/zoau/1.1.1?topic=installing-configuring-zoa-utilities). 

Also note that that ZOAU 1.0.3 can only be used with [Ansible Core less than or equal to v1.2.1](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#version-1-2-1)
