### ISSUE TITLE
[cloud_infra_center] bastion template mess if domain name has multiple subdomains

### ISSUE THREAD

**Issue by gyohuangxin** [IBM/z_ansible_collections_samples#88]
If cluster name has "-" string like `openshift-cluster1`, the bastion template yaml will be messed:
```
cluster_nodes:
  bootstrap:
    custer1:
      ip: 9.125.72.42
  infra:
    cluster1:
      ip: 9.125.72.51
  masters:
    cluster1:
      etcd: cluster1
      ip: 9.125.72.49

```
